Coloumn Transformer

In [54]:
import numpy as np
import pandas as pd

In [55]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [56]:
df = pd.read_csv('covid_toy.csv')

In [57]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [58]:
df.shape

(100, 6)

In [59]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [60]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [61]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [62]:
df.isna().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [63]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [64]:
x_train

age  gender  fever   cough       city
11   65  Female   98.0    Mild     Mumbai
78   11    Male  100.0    Mild  Bangalore
57   49  Female   99.0  Strong  Bangalore
22   71  Female   98.0  Strong    Kolkata
40   49  Female  102.0    Mild      Delhi
..  ...     ...    ...     ...        ...
6    14    Male  101.0  Strong  Bangalore
15   70    Male  103.0  Strong    Kolkata
83   17  Female  104.0    Mild    Kolkata
37   55    Male  100.0    Mild    Kolkata
13   64    Male  102.0    Mild  Bangalore

[80 rows x 5 columns]

1.

In [71]:
# adding simple imputer to fever column
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])
# also the test data
x_test_fever = si.fit_transform(x_test[['fever']])

x_train_fever

array([[ 98.        ],
       [100.        ],
       [ 99.        ],
       [ 98.        ],
       [102.        ],
       [100.78082192],
       [100.        ],
       [101.        ],
       [103.        ],
       [100.        ],
       [104.        ],
       [ 99.        ],
       [101.        ],
       [103.        ],
       [100.78082192],
       [100.78082192],
       [ 98.        ],
       [104.        ],
       [103.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [100.78082192],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [103.        ],
       [102.        ],
       [ 98.        ],
       [ 98.        ],
       [103.        ],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [104.        ],
       [104.        ],
       [ 98.        ],
       [100.        ],
       [ 99.        ],
       [104

the missing value is replaced by mean of the data

In [ ]:
x_train_fever.shape

In [72]:
# ordinal Encoding -> cough
oe = OrdinalEncoder(categories = [['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [73]:
# OneHot encoding -> gender, city
ohe = OneHotEncoder(drop='first')
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])

x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])

x_train_gender_city.shape

(80, 4)

In [74]:
# extracting age
x_train_age = x_train.drop(columns=['gender','fever','city','cough']).values

x_test_age = x_test.drop(columns = ['gender','fever','cough','city']).values

x_train_age.shape

(80, 1)

In [78]:
x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city.toarray(),x_train_cough),axis=1)

x_test_transformed = np.concatenate((x_test_age,x_test_fever,x_test_gender_city.toarray(),x_test_cough),axis=1)

In [79]:
x_train_transformed.shape

(80, 7)

In [80]:
x_train_transformed

array([[ 65.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 11.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 49.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 71.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 49.        , 102.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 20.        , 100.78082192,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 27.        , 100.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 47.        , 101.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 73.        , 103.        ,   0.        ,   1.        ,
          0.    

2.

In [81]:
from sklearn.compose import ColumnTransformer

In [84]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first'),['gender','city'])
],remainder='passthrough')

In [85]:
transformer.fit_transform(x_train)

array([[ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  65.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  11.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  49.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [102.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  49.        ],
       [100.78082192,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  20.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.    

In [86]:
transformer.fit_transform(x_train).shape

(80, 7)

In [87]:
transformer.transform(x_test).shape

(20, 7)