In [176]:
# data -> 1. Numerical 2. Categorical
                        # Categorical -> 1. Nominal  2. Ordinal

In [177]:
# Nomianal : where categories have no relationship in between or no order
# eg. state in the country we cannot compare them that this state is greater than this

In [178]:
# ordinal : where categories have some relation inbetween or have some order
#  eg. marks in highschool or reviews -> good , excellent, bad


**How to encode categorical data?**

Categorical data consist String values. Machine learning algorithm needs numerical data instead of string values.So we need to encode string values to numerical data , so we can feed it machine learning algorithm.

there many ways to convert categorical data into numerical data but we gonna study two of them :

1. Ordinal Encoding : works on ordinal data

2. One Hot Encoding  : Works on Nominal data

 Label Encoding is similar to ordinal encoding

Let say we have a dataset having input coloumns say 'x' and output column/target value (categorical) say 'y'. then if we want to encode target value/ columns then we cannot use here ordinal encoding , there is another class for it in scikit-learn -> Label Encoder.

It work similarly as ordinal encoder but it is specially designed for output labels.  

Ordinal encoding is used on input label

In [179]:
import numpy as np
import pandas as pd

In [180]:
df = pd.read_csv('customer.csv')

In [181]:
df.sample(5)

age  gender   review education purchased
15   75    Male     Poor        UG        No
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
28   48    Male     Poor    School        No
20   57  Female  Average    School       Yes

when we need to do ordinal, label and nominal encoding. we need seprate these columns and then apply them on the columns

In [182]:
df = df.iloc[:,2:]

In [183]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [184]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [185]:
x_train

review education
15     Poor        UG
47     Good        PG
16     Poor        UG
25     Good    School
13  Average    School
3      Good        PG
39     Poor        PG
9      Good        UG
11     Good        UG
45     Poor        PG
44  Average        UG
12     Poor    School
33     Good        PG
48     Good        UG
43     Poor        PG
6      Good    School
17     Poor        UG
46     Poor        PG
1      Poor        UG
5   Average    School
19     Poor        PG
42     Good        PG
36     Good        UG
14     Poor        PG
27     Poor        PG
49     Good        UG
38     Good    School
2      Good        PG
30  Average        UG
18     Good    School
20  Average    School
8   Average        UG
21  Average        PG
35     Poor    School
7      Poor    School
26     Poor        PG
37  Average        PG
31     Poor    School
4   Average        UG
34  Average    School

In [186]:
from sklearn.preprocessing import OrdinalEncoder

In [187]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
# in this object of ordinal encoder class in which we pass a parameter called categories
# which is going to be a list. In this list we will pass some list->according to the no of
# categorical data eg. if we have two columns , we will pass two list
# -we have to pass  order of the values , if not it will be random

In [188]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [189]:
df.isna().sum()

review       0
education    0
purchased    0
dtype: int64

In [190]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)


In [191]:
x_train

array([[0., 1.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [1., 2.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [1., 2.],
       [0., 0.],
       [1., 1.],
       [1., 0.]])

In [192]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [200]:
from sklearn.preprocessing import LabelEncoder

In [201]:
le = LabelEncoder()

In [202]:
le.fit(y_train)

LabelEncoder()

In [203]:
le.classes_
# here we have no option to decide to which value is given to which
# e.g. No: might get 1 and Yes: might get 0
# or vice-versa

array([0, 1])

In [204]:
y_train  =le.transform(y_train)
y_test = le.transform(y_test)

In [198]:
y_train

array([0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0])