# Numpy

In [494]:
import numpy as np


In [495]:
 np.array([1,2,3,4])#creating simple array

array([1, 2, 3, 4])

In [496]:
a= [1,2,3,"hello"]

In [497]:
a

[1, 2, 3, 'hello']

In [498]:
np.array(a)

array(['1', '2', '3', 'hello'], dtype='<U21')

In [499]:
np.array([1, 2, 3.5])

array([1. , 2. , 3.5])

In [500]:
np.array([[1,2,3],[4,5,6]])#2d array

array([[1, 2, 3],
       [4, 5, 6]])

In [501]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [502]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [503]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [504]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [505]:
np.zeros((4,4,4)).astype(int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [506]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [507]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [508]:
np.linspace(1,5,2)

array([1., 5.])

In [509]:
np.linspace(1,5,3)

array([1., 3., 5.])

In [510]:
np.linspace(1,3,10)

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [511]:
np.linspace(1,5,100)#generate linear spaced number

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [512]:
# Random Generation
np.random.rand(5)#generate number between 0 to 1
# this is normalization

array([0.02615618, 0.82421484, 0.59974401, 0.19361217, 0.15552171])

In [513]:
np.random.rand(3,3)

array([[0.51546868, 0.53974894, 0.89303401],
       [0.00692928, 0.24336347, 0.60781127],
       [0.40332186, 0.50492589, 0.00439514]])

In [514]:
# this is for standardization (3 to -3)

np.random.randn(10)

array([-0.49769554,  0.14189358, -0.48928901, -0.85317181,  1.1403265 ,
       -0.25055516,  0.06699486, -0.13525651,  1.63790285,  0.74116051])

In [515]:
np.random.randint(6)

3

In [516]:
np.random.randint(1,100,10)

array([72, 32, 31, 61, 18, 15, 98,  6, 72,  7])

In [517]:
# Attributes

In [518]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [519]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [520]:
arr.shape

(3, 3)

In [521]:
arr.size

9

In [522]:
arr.dtype

dtype('int64')

In [523]:
# Array Methods

In [524]:
arr.min()

np.int64(1)

In [525]:
arr.max()

np.int64(9)

In [526]:
arr.sum()

np.int64(45)

In [527]:
np.sum(arr,axis=0)#column sum

array([12, 15, 18])

In [528]:
np.sum(arr,axis=1)#row sum

array([ 6, 15, 24])

In [529]:
arr.mean()

np.float64(5.0)

In [530]:
arr.std()

np.float64(2.581988897471611)

In [531]:
arr.argmax()#maximum element index

np.int64(8)

In [532]:
arr.argmin()#minimum element index

np.int64(0)

In [533]:
# Reshaping and Resizing

In [534]:
arr = np.arange(1,31)

In [535]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [536]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [537]:
arr = arr.reshape(6,5)#resize

In [538]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Array Indexing

In [539]:
import numpy as np


In [540]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [541]:
arr[6]

np.int64(17)

In [542]:
arr[1:5:1]

array([12, 13, 14, 15])

In [543]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [544]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [545]:
# arr =arr.reshape(6,5)

In [546]:
arr[5]

array([26, 27, 28, 29, 30])

In [547]:
arr[0,0]

np.int64(1)

In [548]:
arr[0][0]

np.int64(1)

In [549]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [550]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [551]:
arr[:,2]# for column

array([ 3,  8, 13, 18, 23, 28])

In [552]:
# Boolean Indexing

In [553]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [554]:
bool_index = arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [555]:
arr = arr[bool_index]

In [556]:
arr

array([12, 14, 16, 18, 20])

Array Operations

In [557]:
import numpy as np

In [558]:
# Arithmatic operations

In [559]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [560]:
a1

array([1, 2, 3, 4, 5])

In [561]:
a2

array([ 6,  7,  8,  9, 10])

In [562]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [563]:
# a1=np.array([1,2,3,4,5,8]) will give error , size must be same
# a2=np.array([6,7,8,9,10])

In [564]:
a1-a2

array([-5, -5, -5, -5, -5])

In [565]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [566]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [567]:
a1//a2

array([0, 0, 0, 0, 0])

In [568]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [569]:
# Broadcasting

In [570]:
l = [10,20,30,40,50]
arr = np.array(l)

In [571]:
arr+10

array([20, 30, 40, 50, 60])

In [572]:
arr2 =np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [573]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [574]:
# Deep and Shallow Copy

In [575]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [576]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [577]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [578]:
a
b=a

In [579]:
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [580]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [581]:
c=a.copy()

In [582]:
c[0]=10
c

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [583]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [584]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])

In [585]:
mat1

array([[1, 2],
       [3, 4]])

In [586]:
mat2

array([[5, 6],
       [7, 8]])

In [587]:
mat1*mat2# index wise multiplication

array([[ 5, 12],
       [21, 32]])

In [588]:
mat1@mat2# matrix multiplication

array([[19, 22],
       [43, 50]])

In [589]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [590]:
mat1

array([[1, 2],
       [3, 4]])

In [591]:
mat1.T # Transpose

array([[1, 3],
       [2, 4]])

In [592]:
# Stacking Array

In [593]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [594]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [595]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [596]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [597]:
# Splitong Array

In [598]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [599]:
np.hsplit(c,2) #work for equal division

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [600]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# Numpy Exercise

In [601]:
import numpy as np

valid sudoku

In [602]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [603]:
np.sum(s,axis=0) # column

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [604]:
np.sum(s,axis = 1) # row

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [605]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n = s[i:i+3,j:j+3]
    print(n.sum())

45
45
45
45
45
45
45
45
45


General Question

In [606]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [607]:
# shape of the matrix
data.shape

(5, 3)

In [608]:
# average age of student
np.mean(data[:,0])

np.float64(18.4)

In [609]:
# Extract Math Marks Of All Students
data[:,1]

array([85, 92, 76, 65, 90])

In [610]:
# Extract High Science Score
np.max(data[:,2])

np.int64(95)

In [611]:
# get detailsof student who schored more than 90 in maths
bool_index = data[:,1]>90
bool_index

array([False,  True, False, False, False])

In [612]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [613]:
# increase all students mathmark by 5
data[:,1]+=5

In [614]:
# Findhow many student younger than 19
data[data[:,0]<19]

array([[18, 90, 78],
       [17, 81, 95],
       [18, 70, 70]])

In [615]:
# Average marks in each subject
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [616]:
# get data of student who scored at least 80 in both subjects
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [617]:
# Replace all science marks < 75 with 0
data[:,2][data[:,2]<75 ] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])

In [618]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])