In [37]:
import pickle
import numpy as np

In [38]:
ohe_sex=pickle.load(open('ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('ohe_embarked.pkl','rb'))
clf = pickle.load(open('clf.pkl','rb'))

In [39]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [40]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [41]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [42]:
test_input_sex.toarray()

array([[0., 1.]])

In [43]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [44]:
test_input_embarked.toarray()

array([[0., 0., 1.]])

In [45]:
test_input_age=test_input[:,2].reshape(1,1)

In [46]:
test_input_age

array([[31.0]], dtype=object)

In [47]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex.toarray(),test_input_embarked.toarray()),axis=1)

In [48]:
test_input_transformed.shape

(1, 10)

In [55]:
output = clf.predict(test_input_transformed)

In [56]:
output,output.dtype

(array([1]), dtype('int64'))